
import { ActivityLog } from "@/types/activity-logs-types";

export const MOCK_USERS = [
  { id: "user1", name: "Alice Johnson" },
  { id: "user2", name: "Bob Smith" },
  { id: "user3", name: "Carlos Rodriguez" },
  { id: "user4", name: "Diana Wu" },
  { id: "user5", name: "Edward Lee" }
];

export const MOCK_MODULES = [
  { id: "reservations", name: "Reservations" },
  { id: "check-in", name: "Check-in/Check-out" },
  { id: "guest-management", name: "Guest Management" },
  { id: "billing", name: "Billing & Payments" },
  { id: "housekeeping", name: "Housekeeping" },
  { id: "system", name: "System" }
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "log1",
    timestamp: "2025-05-05T10:43:00Z",
    user: MOCK_USERS[0],
    module: "Check-in/Check-out",
    action: "Checked in reservation",
    target: "Reservation #1234 (Room 101)",
    type: "check-in",
    severity: "info",
  },
  {
    id: "log2",
    timestamp: "2025-05-05T11:05:00Z",
    user: MOCK_USERS[1],
    module: "Reservations",
    action: "Updated rate for Deluxe Room",
    target: "Room rate on 2025-06-10 to $150",
    type: "update",
    severity: "info",
  },
  {
    id: "log3",
    timestamp: "2025-05-05T11:15:00Z",
    user: MOCK_USERS[2],
    module: "Housekeeping",
    action: "Marked room as clean",
    target: "Room 202",
    type: "status-change",
    severity: "info",
  },
  {
    id: "log4",
    timestamp: "2025-05-05T09:30:00Z",
    user: MOCK_USERS[3],
    module: "Billing & Payments",
    action: "Processed payment",
    target: "Invoice #5678 ($275.00)",
    type: "payment",
    severity: "info",
  },
  {
    id: "log5",
    timestamp: "2025-05-04T16:20:00Z",
    user: MOCK_USERS[4],
    module: "Guest Management",
    action: "Updated guest profile",
    target: "Guest #8765 (John Doe)",
    type: "update",
    severity: "info",
  },
  {
    id: "log6",
    timestamp: "2025-05-04T14:55:00Z",
    user: MOCK_USERS[0],
    module: "Reservations",
    action: "Created new reservation",
    target: "Reservation #2345 (Guest: Sarah Parker)",
    type: "creation",
    severity: "info",
  },
  {
    id: "log7",
    timestamp: "2025-05-04T11:10:00Z",
    user: MOCK_USERS[1],
    module: "Check-in/Check-out",
    action: "Checked out guest",
    target: "Room 305 (Guest: Michael Brown)",
    type: "check-out",
    severity: "info",
  },
  {
    id: "log8",
    timestamp: "2025-05-03T08:45:00Z",
    user: MOCK_USERS[2],
    module: "System",
    action: "Failed login attempt",
    target: "IP: 192.168.1.25",
    type: "security",
    severity: "warning",
  },
  {
    id: "log9",
    timestamp: "2025-05-03T17:30:00Z",
    user: MOCK_USERS[3],
    module: "Reservations",
    action: "Cancelled reservation",
    target: "Reservation #3456",
    type: "cancellation",
    severity: "info",
  },
  {
    id: "log10",
    timestamp: "2025-05-03T13:15:00Z",
    user: MOCK_USERS[4],
    module: "Billing & Payments",
    action: "Issued refund",
    target: "Transaction #9012 ($120.00)",
    type: "refund",
    severity: "info",
  },
  {
    id: "log11",
    timestamp: "2025-05-02T10:20:00Z",
    user: MOCK_USERS[0],
    module: "Housekeeping",
    action: "Reported maintenance issue",
    target: "Room 407 (Plumbing)",
    type: "maintenance",
    severity: "warning",
  },
  {
    id: "log12",
    timestamp: "2025-05-02T09:05:00Z",
    user: MOCK_USERS[1],
    module: "Guest Management",
    action: "Added VIP status",
    target: "Guest #7654 (Elizabeth Taylor)",
    type: "update",
    severity: "info",
  },
  {
    id: "log13",
    timestamp: "2025-05-02T16:40:00Z",
    user: MOCK_USERS[2],
    module: "System",
    action: "Generated night audit report",
    target: "Report #1234",
    type: "report",
    severity: "info",
  },
  {
    id: "log14",
    timestamp: "2025-05-01T11:30:00Z",
    user: MOCK_USERS[3],
    module: "Billing & Payments",
    action: "Payment failed",
    target: "Invoice #6789 (Declined card)",
    type: "payment-error",
    severity: "error",
  },
  {
    id: "log15",
    timestamp: "2025-05-01T14:15:00Z",
    user: MOCK_USERS[4],
    module: "Housekeeping",
    action: "Room status changed to out-of-order",
    target: "Room 512 (Renovation)",
    type: "status-change",
    severity: "info",
  },
  {
    id: "log16",
    timestamp: "2025-05-01T08:30:00Z",
    user: MOCK_USERS[0],
    module: "Reservations",
    action: "Modified reservation dates",
    target: "Reservation #4567 (05/15-05/18 → 05/16-05/19)",
    type: "update",
    severity: "info",
  },
  {
    id: "log17",
    timestamp: "2025-04-30T15:45:00Z",
    user: MOCK_USERS[1],
    module: "Guest Management",
    action: "Deleted guest record",
    target: "Guest #6543 (Test Account)",
    type: "deletion",
    severity: "warning",
  },
  {
    id: "log18",
    timestamp: "2025-04-30T12:10:00Z",
    user: MOCK_USERS[2],
    module: "System",
    action: "System backup completed",
    target: null,
    type: "system-maintenance",
    severity: "info",
  },
  {
    id: "log19",
    timestamp: "2025-04-30T09:55:00Z",
    user: MOCK_USERS[3],
    module: "Check-in/Check-out",
    action: "Performed late check-out",
    target: "Room 209 (Guest: Robert Johnson)",
    type: "check-out",
    severity: "info",
  },
  {
    id: "log20",
    timestamp: "2025-04-29T17:20:00Z",
    user: MOCK_USERS[4],
    module: "Billing & Payments",
    action: "Added room charge",
    target: "Folio #7890 (Mini Bar $25.00)",
    type: "charge",
    severity: "info",
  }
];
