// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwfqscfouyzxziasqomv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZnFzY2ZvdXl6eHppYXNxb212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MzIwNDMsImV4cCI6MjA1MzEwODA0M30.rXriaGoC4tG1gTK378rie9xQHhpaMh7k31VbLJwIN54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);